### ISSUE TITLE
Deprecate `web` and `shell` in one block

### ISSUE THREAD

**Issue by chillum** [chillum/jsonmon#10]
Someday we will drop `web` and `shell` in one block. That is:
```yaml
- name:   Yandex
  shell:  ping localhost
  web:    http://localhost
```
I'm not sure, if there are real users of this undocumented feature, but this will give very strange notifications.
